# Generated by Django 2.1.2 on 2019-01-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='team',
            new_name='belonging_team',
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
            preserve_default=False,
        ),
    ]
