# Generated by Django 2.1.2 on 2019-01-01 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='address', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='date_of_incorporation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
