# Generated by Django 2.1.2 on 2019-01-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190101_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_of_incorporation',
        ),
    ]
